development:
  adapter: sqlite3
  database: db/wordle_development.sqlite3

test:
  adapter: sqlite3
  database: db/wordle_test.sqlite3

production:
  adapter: sqlite3
  database: db/wordle_production.sqlite3
